/*
 * The files that turn a class into a PROJECT - what "New Project from
 * Template" writes.
 *
 * Why this exists: "New App from Template" hands out one class, at the cursor
 * or as an untitled document. That is the right thing when you already have a
 * repository. When you do not, it leaves the user with the one artefact the
 * extension cannot check properly: no `abap2ui5lint.jsonc` means the view
 * check falls back to VS Code settings, and the first CI run in that
 * repository disagrees with what the editor had been saying. The config the
 * extension itself searches for is the thing a new project was missing.
 *
 * WHERE THE CONTENT COMES FROM. abap2UI5/app-template is the ecosystem's
 * starting point, and everything in it that does not carry the template's own
 * name is copied here VERBATIM from `data/app-template.json` - a snapshot
 * regenerated by `npm run app-template` and refreshed weekly by
 * `.github/workflows/bump-app-template.yml`. Copied, not re-typed, because
 * re-typed is what this file used to do and the copy had drifted: it emitted
 * `@abap2ui5/linter@^0.1.1` while the ecosystem was on 0.2.1, no framework pin
 * at all (a scaffolded project therefore resolved abap2UI5's moving default
 * branch - the exact failure app-template's config comment documents), no
 * `chain-house-layout` rule, and no AGENTS.md, so an agent starting a project
 * from inside the IDE got no briefing at all.
 *
 * Generated rather than cloned, still, and deliberately: `abap2ui5.newProject`
 * is registered by the WEB entry too (`src/web/extension.ts`, no `when`
 * clause hiding it), and in vscode.dev there is no git, no child process and
 * no guarantee of network. An offline, deterministic scaffold is also
 * testable, which the rest of this extension is built to be.
 *
 * What is still WRITTEN here, and why: everything that has to know the
 * project's name or the class's name - README, `.abapgit.xml`,
 * `package.devc.xml`, `package.json`, the AGENTS.md header, the CI workflow
 * (the template's own runs a `scripts/check-pin.mjs` this scaffold does not
 * write). Those files take their moving parts - dependency versions, shared
 * script bodies, the linter action's pin, the framework pin - out of the
 * snapshot rather than repeating them, so there is nothing left to drift.
 * `src/test/scaffold.test.ts` is the gate over exactly that.
 *
 * `vscode`-free on purpose: the content is data, so the test suite runs every
 * generated class through the bundled linter the same way it does the
 * single-class templates.
 */

import { AppTemplate, templateSource } from "./template";
import appTemplate from "./data/app-template.json";

/** app-template's files, exactly as that repository has them. */
export const TEMPLATE_FILES: Record<string, string> = appTemplate.files;

/** app-template's own description of what a project takes from it - the file
 *  lists and the substitutions, snapshotted with the files themselves. One
 *  list, in the repository that owns it; `npm run rename` over there and
 *  ai-mcp's `scaffold_app` execute the same one. */
export const TEMPLATE_SPEC = appTemplate.template;

/* The shared files this scaffold does NOT copy byte for byte, because it
 * writes its own around values read out of them: the manifest (project name,
 * and the two scripts that need a `scripts/` directory a project does not
 * get), the CI workflow (same, plus the linter action's pin), and AGENTS.md
 * (its head describes THIS project; the guide below the marker is mirrored).
 * Everything else app-template calls shared is copied - so a file added over
 * there arrives here without an edit. */
const COMPOSED = new Set(["package.json", ".github/workflows/check.yml", "AGENTS.md"]);

/** The template's shared files this scaffold copies unchanged. */
export const VERBATIM_FILES: string[] = TEMPLATE_SPEC.files.shared.filter(
  (f: string) => !COMPOSED.has(f)
);

/** Everything from this line down in app-template's AGENTS.md is the mirrored
 *  app-building guide - repo-independent, and what a new project needs most. */
export const GUIDE_MARKER = "> **Provenance:**";

export interface ScaffoldFile {
  /** Path relative to the project root, POSIX separators. */
  path: string;
  content: string;
  /** abapGit serializes its XML with a UTF-8 BOM, and a BOM-less file comes
   *  back changed on the first pull - for everyone. */
  bom?: boolean;
}

/** abapGit derives the object name from the file name, so it has to match. */
const sidecar = (className: string): string =>
  `<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_CLAS" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <VSEOCLASS>
    <CLSNAME>${className.toUpperCase()}</CLSNAME>
    <LANGU>E</LANGU>
    <DESCRIPT>abap2UI5 app</DESCRIPT>
    <STATE>1</STATE>
    <CLSCCINCL>X</CLSCCINCL>
    <FIXPT>X</FIXPT>
    <UNICODE>X</UNICODE>
   </VSEOCLASS>
  </asx:values>
 </asx:abap>
</abapGit>
`;

/** The framework release app-template pins abaplint's clone to - named in the
 *  scaffolded AGENTS.md so the reader installs the release the lint assumes. */
export function frameworkPin(): string {
  const m = /"branch":\s*"([^"]+)"/.exec(TEMPLATE_FILES["abaplint.jsonc"]);
  return m ? m[1] : "";
}

/** The linter action reference (SHA pin + tag comment) app-template's own
 *  workflow uses. Taken from there rather than repeated, so the scaffolded
 *  workflow cannot end up on a different version of the action than the
 *  template a user is told to compare against. */
export function linterActionRef(): string {
  const m = /^\s*uses:\s*(abap2UI5\/linter@.*)$/m.exec(
    TEMPLATE_FILES[".github/workflows/check.yml"]
  );
  // The bare major tag is what the linter's README documents; it is the right
  // fallback if the template ever stops pinning, and never silently wrong.
  return m ? m[1].trim() : "abap2UI5/linter@v0";
}

/** The mirrored app-building guide out of app-template's AGENTS.md. */
export function guideSection(): string {
  const text = TEMPLATE_FILES["AGENTS.md"];
  const at = text.indexOf(GUIDE_MARKER);
  return at === -1 ? "" : text.slice(at);
}

/*
 * The AGENTS.md a new project gets. The HEAD is written here because it
 * describes THIS project (its class, its scripts, the extension that made
 * it); everything below the provenance block is app-template's mirrored
 * guide, byte for byte, so an agent reading it here reads exactly what an
 * agent in a template-based repository reads.
 */
const AGENTS = (projectName: string, className: string): string =>
  `# AGENTS.md — ${projectName}

Briefing for AI assistants (and humans) developing **this abap2UI5 app
repository**. It was created by the
[abap2UI5 VS Code extension](https://github.com/abap2UI5/vscode-extension)
("abap2UI5: New Project from Template"), which writes the same gates and the
same guide as
[abap2UI5/app-template](https://github.com/abap2UI5/app-template) — that
repository is the fuller article (it also ships an \`npm run rename\`, a
LICENSE and a pin gate) and is where all of this is maintained.

## This repository

| Path | Purpose |
| --- | --- |
| \`src/\` | The app classes (abapGit project, \`STARTING_FOLDER=/src/\`, \`FOLDER_LOGIC=PREFIX\`) — one class per app, named \`ZCL_*\` |
| \`src/${className}.clas.abap\` | The starter app — copy it for your next app (keep the \`.clas.xml\` sidecar's \`CLSNAME\` in sync) |
| \`package.json\` | The two gates as devDependencies (\`@abaplint/cli\`, \`@abap2ui5/linter\` + \`@abap2ui5/render-runtime\`) and the \`npm run check*\` scripts. **Commit the \`package-lock.json\` the first install writes** — it is what makes CI and your machine run the same versions, and CI's \`npm ci\` needs it |
| \`abaplint.jsonc\` | abaplint config; abaplint clones the abap2UI5 framework for dependency resolution, pinned to release tag \`${frameworkPin()}\` (\`"branch"\` — abaplint passes it to \`git clone --branch\`, which takes a tag; there is no \`"tag"\` key). Bump the pin when you need a newer API, and run \`npm run check\` |
| \`abap2ui5lint.jsonc\` | [abap2UI5-linter](https://github.com/abap2UI5/linter) config (paths, UI5 floor, distribution, rule severities, fail level) — CLI flags override it, and **the VS Code extension reads this same file**, so the editor and CI judge your views by the same rules |
| \`.github/workflows/check.yml\` | CI: abaplint from the lockfile, then the abap2UI5-linter through its own action for the static gate + headless render of every view |

## Build & verify — run before every commit

\`\`\`bash
npm install                     # once - installs both gates and writes the
                                # lockfile CI needs (commit it)
npx playwright install chromium # once - only the render gate needs a browser

npm run check                   # abaplint + linter, expect 0 issues
npm run check:abap2ui5:fast     # fast loop: linter without the render gate
npm run fix                     # apply the linter's mechanical corrections
\`\`\`

Both gates run offline from any SAP system (abaplint clones the framework on
first use, so it needs network). Deploy to a system via
[abapGit](https://abapgit.org/) and start an app with
\`<icf-endpoint>?app_start=${className}\`.

In the editor, the extension shows the same findings as diagnostics with quick
fixes while you type; F9 launches the class in an embedded preview against a
real system, and "Preview View (No System)" renders it without one.

Conventions: every \`.clas.abap\` needs its \`.clas.xml\` sidecar (UTF-8 **with
BOM**, LF endings — copy an existing one); class names stay in \`ZCL_*\`; the
whole repo is in English.

The rest of this file is the complete app-building reference — read it before
writing or changing any app class.

${guideSection()}`;

const CHECK_WORKFLOW = (): string =>
  `# The two gates every abap2UI5 app repo gets for free - both run without an
# SAP system:
#
#   abaplint       - ABAP syntax and style, with the abap2UI5 framework cloned
#                    as a dependency so z2ui5_* names resolve
#   abap2ui5lint   - the abap2UI5-linter: the app class and the view it builds,
#                    checked together (controls, properties, UI5 version floor,
#                    bindings, builder-tree defects) plus a headless
#                    XMLView.create render of every view
#
# abaplint runs from this repository's devDependencies, so CI and
# \`npm run check\` on your machine use the version package-lock.json names. The
# abap2UI5-linter runs as its own GitHub Action: it brings the ~118 MB UI5
# runtime and the Chromium the render gate needs, and takes every setting it is
# not given from abap2ui5lint.jsonc - so paths, UI5 floor, rule severities and
# the fail level stay decided by the config in this repo. Keep the action pin
# and the \`@abap2ui5/linter\` devDependency on the same release line, or the two
# can eventually disagree about a rule.
#
# The actions are pinned to a COMMIT rather than to a major tag: a tag is a
# pointer its owner can move, so a job runs whatever it points at that day.
# The tag stays in the comment so the version is readable, and
# \`.github/dependabot.yml\` moves the pins so they do not go stale.
name: check

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: check-\${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22'
          cache: 'npm'

      # Both this and the cache above read package-lock.json, which \`npm
      # install\` wrote for you the first time - commit it. That file is the
      # whole reason a green \`npm run check\` on your machine means this job
      # passes: it is the same resolved versions on both sides.
      - run: npm ci

      - name: abaplint (expect 0 issues)
        run: npx abaplint abaplint.jsonc

      # Settings come from abap2ui5lint.jsonc, which asks for the render gate
      # ("render": true) - so a runtime that failed to install fails this step
      # instead of being skipped with a warning under a green check. Findings
      # are annotated onto the pull request diff automatically.
      - name: abap2UI5-linter (property gate + headless render)
        uses: ${linterActionRef()}

      # The same report as markdown on the run's own page - property gate only,
      # since the step above already decided whether the views load.
      - name: Job summary
        if: always()
        run: npx abap2ui5lint --no-render --advisory --no-progress --format markdown >> "$GITHUB_STEP_SUMMARY"
`;

const README = (projectName: string, className: string): string =>
  `# ${projectName}

An [abap2UI5](https://github.com/abap2UI5/abap2UI5) app: UI5 in the browser,
written purely in ABAP.

## Run it

1. Install the abap2UI5 framework in your system with
   [abapGit](https://abapgit.org), and set up its HTTP handler
   ([documentation](https://abap2ui5.github.io/docs/get_started/quickstart)).
   The gates here lint against release **${frameworkPin()}** (pinned in
   \`abaplint.jsonc\`), so install that one or newer.
2. Pull this repository with abapGit too.
3. Open \`<your endpoint>?app_start=${className.toUpperCase()}\`.

## Check it, without a system

\`\`\`sh
npm install                       # once - and commit the package-lock.json
npx playwright install chromium   # once, for the render gate
npm run check
\`\`\`

\`npm run check\` is what CI runs: abaplint for the ABAP, and the
[abap2UI5-linter](https://github.com/abap2UI5/linter) for the class and the
view it builds together - including loading every view in a real browser.
\`npm run fix\` applies what can be applied.

The VS Code extension reads the same \`abap2ui5lint.jsonc\`, so the editor and
CI never disagree.

## Make it yours

The class is \`${className.toUpperCase()}\`; rename it in
\`src/${className}.clas.abap\` **and** in the \`CLSNAME\` of its \`.clas.xml\`
(\`xml_consistency\` fails the check if only one moves). \`.abapgit.xml\` carries
the repository name, \`src/package.devc.xml\` the ABAP package description.
Your namespace is a one-time decision too: \`object_naming\` in
\`abaplint.jsonc\` requires \`^ZCL_\`/\`^ZCX_\`.

## Where this came from

[AGENTS.md](AGENTS.md) is the complete app-building reference — read it (or
point your AI assistant at it) before writing an app class. Everything below
its provenance block is mirrored from the abap2UI5 framework's own guide, and
the gates around it are the ones
[abap2UI5/app-template](https://github.com/abap2UI5/app-template) ships. That
repository is the fuller starting point — same files, plus an
\`npm run rename\`, a LICENSE and a framework-pin gate.
`;

/*
 * Only the identity fields are decided here. The dependency versions and the
 * script bodies come from app-template's own package.json, because a hand-kept
 * second copy of "which linter version does a new project get" is exactly the
 * thing that was wrong: this file shipped ^0.1.1 for two releases of 0.2.x.
 */
const PACKAGE_JSON = (projectName: string): string => {
  const template = JSON.parse(TEMPLATE_FILES["package.json"]) as {
    scripts: Record<string, string>;
    devDependencies: Record<string, string>;
    engines?: Record<string, string>;
    /** app-template carries an `overrides` block while the published linter's
     *  peer range is narrower than the render-runtime it is released beside -
     *  without it `npm ci` refuses the very pairing the template documents.
     *  Copied rather than judged: it is a fact about the registry, and the
     *  template is where it is decided and where it will be removed. */
    overrides?: Record<string, unknown>;
  };
  const scripts: Record<string, string> = {};
  for (const [name, body] of Object.entries(template.scripts)) {
    // The template's `rename` and `check:pin` run files out of its `scripts/`
    // directory, which this scaffold does not write - a script that cannot run
    // is worse than one that is not offered.
    if (!body.includes("scripts/")) {
      scripts[name] = body;
    }
  }
  return `${JSON.stringify(
    {
      name: projectName,
      private: true,
      version: "1.0.0",
      description: "abap2UI5 app",
      scripts,
      devDependencies: template.devDependencies,
      engines: template.engines ?? { node: ">=22" },
      ...(template.overrides ? { overrides: template.overrides } : {}),
    },
    null,
    2
  )}\n`;
};

/**
 * Every file a new abap2UI5 project needs, as data.
 *
 * @param projectName  repository/npm name, e.g. `my-app`
 * @param className    the app class, lower case, e.g. `zcl_my_app`
 */
export function scaffoldFiles(
  projectName: string,
  className: string,
  template: AppTemplate
): ScaffoldFile[] {
  const cls = className.toLowerCase();
  return [
    { path: `src/${cls}.clas.abap`, content: `${templateSource(template, cls)}\n` },
    { path: `src/${cls}.clas.xml`, content: sidecar(cls), bom: true },
    {
      path: "src/package.devc.xml",
      bom: true,
      content: `<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_DEVC" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <DEVC>
    <CTEXT>${projectName}</CTEXT>
   </DEVC>
  </asx:values>
 </asx:abap>
</abapGit>
`,
    },
    {
      path: ".abapgit.xml",
      bom: true,
      content: `<?xml version="1.0" encoding="utf-8"?>
<asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
 <asx:values>
  <DATA>
   <NAME>${projectName}</NAME>
   <MASTER_LANGUAGE>E</MASTER_LANGUAGE>
   <STARTING_FOLDER>/src/</STARTING_FOLDER>
   <FOLDER_LOGIC>PREFIX</FOLDER_LOGIC>
  </DATA>
 </asx:values>
</asx:abap>
`,
    },
    // Verbatim from app-template - see the header. These are the files that
    // decide what a project is checked by, and there is one source for them:
    // app-template's template.json says which they are, so a file added over
    // there is handed out here without anybody editing this list.
    ...VERBATIM_FILES.map((path) => ({ path, content: TEMPLATE_FILES[path] })),

    { path: "package.json", content: PACKAGE_JSON(projectName) },
    { path: ".github/workflows/check.yml", content: CHECK_WORKFLOW() },
    { path: "AGENTS.md", content: AGENTS(projectName, cls) },
    { path: "README.md", content: README(projectName, cls) },
  ];
}

/** Built rather than written literally: an invisible character in a source
 *  file is the kind of thing an editor, a formatter or a paste drops without
 *  anyone noticing. */
const BOM = String.fromCharCode(0xfeff);

/**
 * The exact text to write for one scaffold file - the BOM belongs to the
 * content, so that whether a file gets one is decided (and tested) here
 * rather than at the call site.
 */
export function scaffoldText(file: ScaffoldFile): string {
  return file.bom ? BOM + file.content : file.content;
}

/** npm package names: lower case, no spaces, no leading dot or underscore. */
export function projectNameFrom(folderName: string): string {
  const name = folderName
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^[._-]+/, "")
    .replace(/-+$/, "");
  return name || "abap2ui5-app";
}
